### ISSUE TITLE
[PHPStan] Return typehint of method ModelTransformerInterface::transform() has invalid type object.

### ISSUE THREAD

**Issue by Comrade42** [tonicforhealth/model-transformer#1]
If I run the [PHPStan](https://github.com/phpstan/phpstan) analyser over a class that implements the `\Tonic\Component\ApiLayer\ModelTransformer\ModelTransformerInterface` interface, I got the following error:
> Return typehint of method FooBarTransformer::transform() has invalid type object.

**Comment by krasun** [comment]
Thanks!
